#!/bin/bash

case "${1}" in
  configure)
    echo "Enabling & starting Waggle Wagman Watchdog Service"
    systemctl enable waggle-wagman-watchdog.timer
    systemctl start waggle-wagman-watchdog.timer || true
    ;;
esac
