#!/bin/bash

case "${1}" in
  configure)
    echo "Enabling & starting Sage Wagman Watchdog Service"
    systemctl enable sage-wagman-watchdog.timer
    systemctl start sage-wagman-watchdog.timer || true
    ;;
esac
